### ISSUE TITLE
nChunks, nChunks2, nTastks, mc.cores, chunkSize

### ISSUE THREAD

**Issue by gdlc** [QuantGen/BGData#32]
We need to consolidate this.

Clearly we need one keyword to define the number of columns brought to RAM at a time, we need a different term to define how many cores used to process each chunk and probably a different term to define the block size in symDMatrix.

Here is a proposal
- nChunks: define the size of the chunk to be brought to RAM.
- chunkSize: used also to define the size of the chunk to brought  to RAM. I suggest chunkSize over-rides nChunks.
- nTasks used to define the number of tasks used to process one chunk.
- mc.cores, I suggest to set it by default to min(detctCores(), nTasks)
- blockSize: the number of columns/rows of a block in a symDMatrix

**Comment by agrueneberg** [comment]
Agreed on all of them except `mc.cores` because `detectCores()` is not reliable on the cluster and `nTasks` is undefined if not specified. I would further suggest to rename `mc.cores` to `nCores` in case a better multicore package comes along in the future. I think `blockSize` could also use a complementary `nBlocks` just like the chunking does.

**Comment by gdlc** [comment]
sounds good. note that if we set mc.cores (or nCores) to min(detectCores(),nTasks) we will control everything with nTasks. If nTasks has default value of 1, then we will just be assuming that the user will not send a job requestin x cores and then use in the scripts nTasks>x.

In any case this won't be a big deal because it is just a matte of how to define default values.  We also need to think carefully about setting default values. I suggest chunkSize and blockSize will preceed over nChunks and nBlocks.
